services:
  redis-vulnerable:
    image: redis-chestnut-normal
    container_name: redis-chestnut-normal-container
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    ports:
      - "6381:6379"
  redis-seccomp:
    image: redis-chestnut-seccomp
    container_name: redis-chestnut-seccomp-container
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    ports:
      - "6382:6379"
    cap_add:
      - SYSLOG
    security_opt:
      - seccomp=unconfined
